[package]
name = "rasmusmerzin/playerlist"
description = "PlayerList controller displays children of Players."
version = "1.0.2"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1"
Timer = "sleitnick/timer@1"
