[package]
name = "rasmusmerzin/crouch"
description = "Crouch module."
version = "0.1.2"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1"
Trove = "sleitnick/trove@0.5"
