[package]
name = "rasmusmerzin/firstperson"
description = "First person shooter module."
version = "0.1.24"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Damage = "rasmusmerzin/damage@1"
Component = "sleitnick/component@2"
Knit = "sleitnick/knit@1"
Trove = "sleitnick/trove@0.5"
Timer = "sleitnick/timer@1"
