[package]
name = "rasmusmerzin/supabase"
description = "Minimal Supabase client class"
version = "0.1.0"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
