[package]
name = "rasmusmerzin/tools"
description = "Tool bundle."
version = "0.3.15"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Component = "sleitnick/component@2"
Knit = "sleitnick/knit@1"
Trove = "sleitnick/trove@0.5"
Signal = "sleitnick/signal@1"
compose = "rasmusmerzin/compose@1"
