[package]
name = "rasmusmerzin/arc"
description = "Arc class"
version = "0.3.3"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
