[package]
name = "rasmusmerzin/damage"
description = "Damage module."
version = "1.0.1"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1"
Message = "rasmusmerzin/message@1"
Signal = "sleitnick/signal@1"
