[package]
name = "rasmusmerzin/message"
description = "Bundle of services for sending messages to clients."
version = "0.1.1"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1"
Maid = "rasmusmerzin/maid@1"
Signal = "sleitnick/signal@1"
StackQueue = "rasmusmerzin/stackqueue@1"
compose = "rasmusmerzin/compose@1"
