[package]
name = "rasmusmerzin/granary"
description = "First person shooter module."
version = "0.2.1"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Admin = "rasmusmerzin/admin@1"
Message = "rasmusmerzin/message@1"
Component = "sleitnick/component@2"
Knit = "sleitnick/knit@1"
Signal = "sleitnick/signal@1"
Trove = "sleitnick/trove@0.5"
Timer = "sleitnick/timer@1"
