[package]
name = "rasmusmerzin/admin"
description = "Admin commands module."
version = "0.4.0"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1"
Message = "rasmusmerzin/message@1"
