[package]
name = "rasmusmerzin/bar"
description = "Bar controller. Clock and Health UI."
version = "1.0.0"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1"
Timer = "sleitnick/timer@1.1"
compose = "rasmusmerzin/compose@1"
