[package]
name = "rasmusmerzin/stackqueue"
description = "StackQueue class"
version = "1.0.0"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
