[package]
name = "rasmusmerzin/backpack"
description = "Backpack controller displays children of Backpack."
version = "0.3.1"
license = "MIT"
authors = ["Emil Rasmus Merzin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1"
Timer = "sleitnick/timer@1"

