[package]
name = "simple-magic/rbx-util"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Admin = "rasmusmerzin/admin@1"
Bar = "rasmusmerzin/bar@1"
Crouch = "rasmusmerzin/crouch@0"
FirstPerson = "rasmusmerzin/firstperson@0"
Knit = "sleitnick/knit@1"
Message = "rasmusmerzin/message@1"
PlayerList = "rasmusmerzin/playerlist@1"
Repository = "rasmusmerzin/repository@1"
Timer = "sleitnick/timer@1"
Trove = "sleitnick/trove@0.5"
compose = "rasmusmerzin/compose@1"
