[package]
name = "simple-magic/rbx-util"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Admin = "rasmusmerzin/admin@0"
Arc = "rasmusmerzin/arc@0"
Backpack = "rasmusmerzin/backpack@0"
Bar = "rasmusmerzin/bar@1"
Knit = "sleitnick/knit@1"
Maid = "rasmusmerzin/maid@1"
Message = "rasmusmerzin/message@1"
PlayerList = "rasmusmerzin/playerlist@1"
Repository = "rasmusmerzin/repository@1"
StackQueue = "rasmusmerzin/stackqueue@1"
Timer = "sleitnick/timer@1"
compose = "rasmusmerzin/compose@1"
